package controller;

import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import model.DB_Model;

/*The controller for the login view*/
public class loginController {
	
	@FXML
    private AnchorPane root;
	
	@FXML
	private Button btnLogin;
	@FXML
	private TextField labelCF;
	@FXML
	private PasswordField labelPassword;
	
	@FXML
    private RadioButton radioBtnPatient;

    @FXML
    private RadioButton radioBtnPhysician;

	
	// Event Listener on Button[#btnLogin].onAction
	@FXML
	public void btnLoginOnClicked(ActionEvent event) {
		
		boolean isRadioBtnPhysicianSelected = radioBtnPhysician.isSelected();
		boolean isRadioBtnPatientSelected = radioBtnPatient.isSelected();
		
		// TODO Autogenerated
		DB_Model db = null;
		try {
			db = DB_Model.getInstance();
			if (isRadioBtnPhysicianSelected) {
				String q = "SELECT * FROM physician WHERE CF='" + labelCF.getText() + "' AND password='" + labelPassword.getText() + "';";
				ResultSet st = null;
				st = db.runQuery(q);
				labelCF.setText("");
				labelPassword.setText("");
				if (st.getString("CF") == null) {
					Alert alert = new Alert(Alert.AlertType.ERROR);
			        alert.setTitle("Error Physician");
			        alert.setHeaderText("No result");
			        alert.showAndWait();
				}else {
					System.out.println(st.getString("CF"));
					System.out.println("Andiamo in un'altra schermata Physician");
				}
			}else if(isRadioBtnPatientSelected){
				String q = "SELECT * FROM patient WHERE CF='" + labelCF.getText() + "' AND password='" + labelPassword.getText() + "';";
				ResultSet st = null;
				st = db.runQuery(q);
				labelCF.setText("");
				labelPassword.setText("");
				if (st.getString("CF") == null) {
					Alert alert = new Alert(Alert.AlertType.ERROR);
			        alert.setTitle("Error Patient");
			        alert.setHeaderText("No result");
			        alert.showAndWait();
				}else {
					System.out.println(st.getString("CF"));
					System.out.println("Andiamo in un'altra schermata Patient");
				}
			}else {
				Alert alert = new Alert(Alert.AlertType.ERROR);
		        alert.setTitle("Devi selezionare almeno uno dei due campi");
		        alert.setHeaderText("Mona");
		        alert.showAndWait();
				return;
			}
			

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//System.out.println("CF: "+ labelCF.getText() + ", Password: " + labelPassword.getText());
		System.out.println("Button Clicked!");
	}
	
	@FXML
    void radioBtnPatientSelected(ActionEvent event) {
		System.out.println("Patient selected/non selected");
		radioBtnPhysician.setSelected(false);
    }

    @FXML
    void radioBtnPhysicianSelected(ActionEvent event) {
    	System.out.println("Physician selected/non selected");
    	radioBtnPatient.setSelected(false);
    }
	
	
	/*Handling the closing event*/
	public void handleCloseRequest(javafx.stage.WindowEvent windowEvent) {
        // Handle the close request event
        // Here you can show a confirmation dialog or perform any necessary cleanup
        // before closing the application
		try {
			DB_Model db = DB_Model.getInstance();
			db.closeConnection();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println("Chiusura");
        windowEvent.consume(); // Consume the event to prevent the default close action
        closeApplication();
    }

	/*Closes the application*/
    private void closeApplication() {
        // Close the application
        Stage stage = (Stage) root.getScene().getWindow();
        stage.close();
    }
	
}
